#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# pylint: disable=W1203
# pylint: disable=W0613

import sys
import Ice
Ice.loadSlice('IceGauntlet.ice')
# pylint: disable=E0401
# pylint: disable=C0413

import IceGauntlet
 
class Client(Ice.Application):
    def run(self, argv): 
        base = self.communicator().stringToProxy(argv[1])
        autenticacion = IceGauntlet.GestorMapasPrx.checkedCast(base)
    
        if not autenticacion:
            raise RuntimeError("Invalid proxy")

        autenticacion.remove(argv[2], argv[3])

        return 0

sys.exit(Client().main(sys.argv))

